spring:
  application:
    name: canchitas

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/canchitas_management_pruebas}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:admin}

  jpa:
    show-sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

